version: '3'

services:
  flask-app:
    build: ./web
    restart: always
    environment:
      - MYSQL_DATABASE_HOST=mysql-db
    depends_on:
      - mysql-db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - server_net
    volumes:
      - uploads:/app/uploads

  mysql-db:
    build: ./db
    restart: always
    ports:
      - "3306:3306"
    networks:
      server_net:
        ipv4_address: 10.0.1.10
  
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8085:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - server_net
    depends_on:
      - flask-app

networks:
  server_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.1.0/24"

volumes:
  uploads: